### ISSUE TITLE
SUM on zero returns NaN interval and does not add noise

### ISSUE THREAD

**Issue by ankit-oss** [opendifferentialprivacy/smartnoise-sdk#128]
When D1 is single zero element [0] with min and max set as 0, SELECT SUM(Usage) AS Usage FROM D1 returns same 0 response on repeated querying and does not add noise to response. This may be because of clamping but it looks odd that no noise gets added on repeated queries. 

Confidence intervals return NaN value.

**Comment by joshua-oss** [comment]
This would be saying sensitivity is zero, right?  If the absence or presence of a user can't possibly change the aggregate, then we don't need noise to hide the contribution.  This would be similar to a constant query like "SELECT 1 FROM D1".  The same constant query will always return the same answer for any neighboring databases, so results will always be indistinguishable.

**Comment by ankit-oss** [comment]
I see. I think if we have auxiliary information that D1 has 1 user's record and D2 has 0 users (by tracking people entering a building), then we can determine from repeated query that the user in D1 has 0 value when we pass a SUM query. 0 could then denote something sensitive like 0 income or 0 marks in exam. 0 sensitivity databases with non zero user count might reveal net new information about the user in D1 that we didn't have when the user was absent in D2 even though query results are same and indistinguishable between D1 and D2. Bin width of histogram will be close to 0. 

The other challenge could be accidental use of numerical columns as enums where 0 indicates having a disease and 1 indicates not having it. So in Metadata, it's easy to mistake a numerical column as a measure when it is indeed categorical.

**Comment by joshua-oss** [comment]
The sensitivity of a count is always 1 * max_contrib.  The bug title refers to SUM.  If the sensitivity of the SUM is always zero, two neighboring databases can never differ by more than zero.

I can't think of a scenario where the first case could happen, because even if you knew the name and SSN of everyone going in the building, the SUM for both queries would need to be identical, per the sensitivity of 0.  Remember that the sensitivity for the column needs to be the same across both neighboring databases, so it wouldn't be valid to have D1 with sensitivity 10 and D2 with sensitivity 0.  And if sensitivity is 0, there should be no way for SUM to be non-zero, because a non-zero SUM implies there is a person or persons who could be removed to eliminate the remainder of the SUM.

For an indicator column with value of 0,1, the sensitivity must be at least 1.  It is not valid to set min and max as 0 if the column can have min of 0 and max of 1.

**Comment by ankit-oss** [comment]
That's correct. SUM query would return zero for both D1 and D2 and sensitivity will be zero for both D1 and D2 in this scenario. 

I was thinking about a case where results are indistinguishable but constant results on repeatedly performing same query can reveal net new information. Empty databases inherit the sensitivity of non-empty databases. If we knew Name and SSN of first patient entering the building, and the patient had zero income, we'd get to know that even though SUM of income was indistinguishable between an empty database without any patient and first patient with zero income. 

SELECT SUM(Income) FROM D2 --> 0 for each of 10K times because database is empty
SELECT SUM(Income) FROM D1 --> 0 for each of 10K times (this means Income of the user in D1 is zero)

Had that user had any other value apart from 0, sensitivity would have instantly become non-zero and the noise would have kicked in for the SUM query. But unfortunately, because the user had a zero income, noise did not kick in and now adversary knows because there was no change in D1 and D2's aggregate query result, User A's column had 0 value in the column being SUM'ed.

**Comment by joshua-oss** [comment]
"Had that user had any other value apart from 0, sensitivity would have instantly become non-zero "

The sensitivity cannot be data-dependent.  The sensitivity cannot change based on some data that comes in or out of the database.  If the sensitivity is 0, and someone with non-zero value is entered, that value would be clamped to 0, and sensitivity would be unchanged.

This is one important reason we didn't include our metadata inference tool in this release.  We don't want people to get confused and think that sensitivity comes from the data.  It needs to be domain-specific.

**Comment by ankit-oss** [comment]
This clarifies for me. So if min and max as per the domain are both zero, we end up with zero sensitivity and not because of the data in database. It might still not be ideal to output NaN in CI intervals for this case. CI interval low and high should perhaps both be zero if sensitivity is zero?

**Comment by joshua-oss** [comment]
This is resolved as by design
