### ISSUE TITLE
We need to update the DPSU vs Korolova test, it is flaky

### ISSUE THREAD

**Issue by eedeleon** [opendifferentialprivacy/smartnoise-sdk#178]
https://github.com/opendifferentialprivacy/whitenoise-system/pull/177 failed even though it is a doc change

It should help to:

- check if the length is greater instead of the sum, it should have less variance
- run the test 100 times( wrap in a for loop while evaluating)
- run 100 times on the current implementation to make sure it catches this bug.
- add a comment about the test so it can be clear to others in the case it fails again later on.

**Comment by joshua-oss** [comment]
@eedeleon, @anujdesai510  Is there some more context on this bug?  Which test is it is referring to?

**Comment by anujdesai510** [comment]
Not sure if it's still a bug but previously the test would occasionally fail. I don't think it ever came up again though so it might be fixed but I can't quite remember.

**Comment by joshua-oss** [comment]
If it's test_dpsu, I've run it several times without failure, so maybe we can close this one?
