### ISSUE TITLE
The SQL PrivateReader does clamping too early

### ISSUE THREAD

**Issue by TedTed** [opendifferentialprivacy/smartnoise-sdk#201]
Currently, the "clamping" only happens at the lowest level: when a table column is called. This means that I can do [attacks like these](https://twitter.com/TedOnPrivacy/status/1263542430089056261) that can trivially leak the data of a user. This is particularly adversarial, but someone could use logic like that without meaning to run an attack (simply because it's convenient) and end up with very different privacy guarantees than what they expect, if any.

Instead, the clamping needs to happen on the values passed to the aggregation. To do that, you need the user to set clamping parameters *in the query*, or you need a way of automatically estimating these bounds (in a DP way), like what is described in [this paper](https://arxiv.org/abs/1909.01917). In the meantime, queries that do anything else than aggregating a know column with metadata should probably be forbidden.

**Comment by joshua-oss** [comment]
Thanks for catching this.  The validator should be prohibiting anything other than simple column select inside aggregations.  We will investigate and fix.

**Comment by joshua-oss** [comment]
PR #210 now prevents analysts from performing expressions inside of aggregations.  Computing sensitivity and stability inside aggregations is not always possible, and something we will delegate to the analysis graph in the future.

**Comment by joshua-oss** [comment]
This has been fixed
