### ISSUE TITLE
In the SQL rewriter, the implementation of AVG underestimates privacy guarantees

### ISSUE THREAD

**Issue by TedTed** [opendifferentialprivacy/smartnoise-sdk#202]
This is a consequence of [this other bug](https://github.com/opendifferentialprivacy/whitenoise-system/issues/200) but it's worth tracking separately, because even if you fix it at the top-level of the rewriter, this will still be a problem: currently, rewriting AVG as SUM/COUNT with the same privacy options will underestimates the ε by a factor of 2, as you're packing 2 aggregations in one.

**Comment by joshua-oss** [comment]
This was fixed in #208 linked from #200
