### ISSUE TITLE
The SQL thresholding math seems off: tau uses a Laplace formula, but the noise is Gaussian

### ISSUE THREAD

**Issue by TedTed** [opendifferentialprivacy/smartnoise-sdk#204]
Looking at `private_reader.py`, it seems that you're using [Gaussian](https://github.com/opendifferentialprivacy/whitenoise-system/blob/60743c0a6bd2002296764a5c388e999c2b99a7dd/sdk/opendp/whitenoise/sql/private_reader.py#L156) as a default mechanism, but the threshold `tau` is computed [based on a Laplace formula](https://github.com/opendifferentialprivacy/whitenoise-system/blob/60743c0a6bd2002296764a5c388e999c2b99a7dd/sdk/opendp/whitenoise/sql/private_reader.py#L123), so it's probably wrong.

This file also imports Laplace but doesn't use it. This should probably be caught by a linter.

**Comment by joshua-oss** [comment]
This is fixed now in #211, merged to master

**Comment by joshua-oss** [comment]
This is fixed now
