### ISSUE TITLE
SQL queries without a "GROUP BY" clause have a weird behavior

### ISSUE THREAD

**Issue by TedTed** [opendifferentialprivacy/smartnoise-sdk#209]
Not critical, just strange: trying to run an SQL query without any GROUP BY returns [only one row](https://twitter.com/TedOnPrivacy/status/1263546652645830659), with very strange results. Not sure what's happening here, but the query should probably fail or return zero rows rather than nonsense.

**Comment by joshua-oss** [comment]
Thanks for flagging this.  We removed a bunch of checks when we decided the analyst would be trusted, but this behavior is definitely wrong.  Adding some checks back in.

**Comment by joshua-oss** [comment]
PR #210 adds check to throw error when analyst runs query with missing aggregation on GROUP BY

**Comment by joshua-oss** [comment]
This is fixed
