### ISSUE TITLE
Caching leads to missing results for certain dimension keys

### ISSUE THREAD

**Issue by ankit-oss** [opendifferentialprivacy/smartnoise-sdk#223]
When caching is set to False (the default case), DP group by test repeatedly succeeds on running 5-10 times. However, when cache_exact is set to True, then the test intermittently fails where sometimes a particular dimension combination in D2 (1 row deleted from D1) like Role: R1, segment: A does not get any values populated even on querying 200 times. 

**GROUP BY query:**
d1_query = "SELECT Role, Segment, COUNT(UserId) AS UserCount, SUM(Usage) AS Usage FROM d1.d1 GROUP BY Role, Segment"
d2_query = "SELECT Role, Segment, COUNT(UserId) AS UserCount, SUM(Usage) AS Usage FROM d2.d2 GROUP BY Role, Segment"

**Caching set to True**
srs = TypedRowset(srs_orig.rows(), list(srs_orig.types.values()))
singleres = private_reader._execute_ast(query_ast, True)

**Repro Steps**

Run the test_groupby test in sdk/evaluation/test_stochastic.py

It is a skipped test right now. So remove that marker. It'll encounter a failure failing at this point intermittently in dp_groupby_query_test method - 

                fD1 = [val[0] for val in d1_d2.iloc[index, n_cols - 3]]
>               fD2 = [val[0] for val in d1_d2.iloc[index, n_cols - 2]]
E               TypeError: 'float' object is not iterable

The reason is fD2 is NaN for that dimension key which is unexpected. It is populated for D1. I checked and in D2 dataset, that dimension combination does exist and the exact COUNT query response is 339. So it's not a small count. 

----------------------------- Captured stdout call -----------------------------
Length of D1:  1000  Length of D2:  999
Index(['role', 'segment', 'usercount_x', 'usercount_y', 'usercount'], dtype='object')
Column:  usercount

**Comment by joshua-oss** [comment]
This is fixed
