### ISSUE TITLE
PATECTGAN has loss function wasserstein, but does not support 

### ISSUE THREAD

**Issue by lurosenb** [opendifferentialprivacy/smartnoise-sdk#278]
Switching to the wasserstein loss function in PATECTGAN breaks the synthesizer.
Either need to support wasserstein, or remove the option

**Comment by Tecnarca** [comment]
I know that removing the option would be easier, but i would like to discuss the possibility of implementing it. 
From the original PATEGAN paper, i get that a wasserstein loss can't easily be used on the teachers (it would require to compute and prove a new bound for the privacy cost) but it can in principle be used on the student. I do not know the implications of doing something like this, but from my understanding it does not compromise the privacy guarantee.

I also do not know if someone is working on this, but i would like to help in extending this model.

**Comment by eedeleon** [comment]
This is great to hear! @Tecnarca  we do not have someone working on this. The team would be happy to review a proposal and help guide you through contributing to the repo if you are interested.

Thanks for reaching out. We have not formalized the process of proposals, so for now a linked github issue with a proposal(if you would like to collaborate on it we can also arrange for that) can get the ball rolling.

**Comment by AprilXiaoyanLiu** [comment]
This is great to hear +1!  @Tecnarca  Look forward to reviewing your proposal and the collaboration!

**Comment by Tecnarca** [comment]
I have proposed the possible extension [here](https://github.com/opendifferentialprivacy/whitenoise-system/pull/288). I hope it is enough to provide a base to further improve from.

**Comment by eedeleon** [comment]
Resolved in https://github.com/opendifferentialprivacy/smartnoise-sdk/pull/288
