### ISSUE TITLE
Push yarrow exact aggregates to SQL backend

### ISSUE THREAD

**Issue by joshua-oss** [opendifferentialprivacy/smartnoise-sdk#29]
Allow rewritten AST to ship processing of exact aggregates to SQL backend, with subsequent noise addition and post-process expression evaluation handled by yarrow

**Comment by Shoeboxam** [comment]
I'm not sure what the integration plan is, but I put together a quick script that demonstrates one way you could substitute SQL backend aggregates into nodes on the graph:
https://github.com/opendifferentialprivacy/whitenoise-core/blob/c6b0522a59acad011731cb9c1b2a0b30d18805a0/bindings-python/tests/test_insertion.py#L1

As you can see, if a private node is inserted in the graph (at any node id), none of the parent nodes will be evaluated, but properties/checks will still be derived/propagated from the materialize.

**Comment by joshua-oss** [comment]
Implemented in #304
